spring:
  datasource:
    url: jdbc:mysql://localhost:3306/markdown_notebook_dev
    username: markdown_notebook
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always