spring:
  datasource:
    url: jdbc:mysql://localhost:3002/markdown_notebook_dev
    username: markdown_notebook
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

client:
  origin: http://localhost:3000
